### ISSUE TITLE
Code logic

### ISSUE THREAD

**Issue by yzaroui** [dmester/sffjs#11]
Hello,

I am reading the code and trying to understand how it works when I came through this:
https://github.com/dmester/sffjs/blob/8971a16f864c72798bc8c600f62ccce42a627237/src/stringformat.js#L483

You are assigning a string array `tokenGroups[1]` to a string `format` that was passed as argument to the method `customNumberFormatter`

```javascript
// Below assigning an array to a string
  if (num < 0 && tokenGroups.length > 1) {
    num *= -1;
    format = tokenGroups[1];
  } else {
    format = tokenGroups[!num && tokenGroups.length > 2 ? 2 : 0];
  }

  // Here using format as if it was still a string!
  for (formatIndex = 0; formatIndex < format.length; formatIndex++) {
    currentToken = format[formatIndex];
```
Could you please explain?

Best,

**Comment by dmester** [comment]
The variable `format` is from [line 490](https://github.com/dmester/sffjs/blob/8971a16f864c72798bc8c600f62ccce42a627237/src/stringformat.js#L490) reused as an array of format tokens. The code above line 490 is tokenizing the format string passed to `customNumberFormatter` and the rest of the function is processing each token to decide what to write to the output string.
