### ISSUE TITLE
Escaping the percent sign

### ISSUE THREAD

**Issue by tsvetelin-pavlov** [dmester/sffjs#2]
It seems, that no matter what I tried, it always calculates percents, when I use custom number format with percent sign, i.e. #,##0.00%%.
I tried escaping with doubling the %, with escape character like #,##0.00\% or with quotes like #,##0.00"%" or #,##0.00'%'.
In all cases I always got the result multiplied by 100 with percent sign behind (i.e. 4,000.00% instead of desired 40.00%).

**Comment by dmester** [comment]
Thanks for the bug report! I will have a look at it and come back to you.

**Comment by dmester** [comment]
This issue should now be fixed in release 1.11. You can escape the percent character in two ways: 0'%' (single or double quotes) or 0\%.
