### ISSUE TITLE
Bad time for en-US culture

### ISSUE THREAD

**Issue by petronellius** [dmester/sffjs#3]
JavaScript Date 00:26:00 with format 'hh:mm:ss tt' is bad formatted to '00:26:00 AM'.
I would expect to see '12:26:00 AM' instead.
Problem is in Date.prototype.__Format function when replacing hour part by numberPair((hour - 1) % 12 + 1). It may fixed by: hour % 12 || 12;

**Comment by dmester** [comment]
Thanks for reporting this issue. It has now been fixed and the fix is included in release 1.13.
