### ISSUE TITLE
Date format string "yyyy" does not pad with leading zeros

### ISSUE THREAD

**Issue by johan-ohrn** [dmester/sffjs#7]
This code produce the wrong output
```
(new Date("0001-01-01")).format('yyyy')
```
output: "1"
expected output: "0001"

```
(new Date("0001-01-01")).format('yy')
```
output: "1"
expected output: "01"

proposed code change:
```
Date.prototype.__Format = function(format) {
	...
	match == "yyyy" ? ("0000" + year).substr(-4) :
	match == "yy"   ? ("00" + year).substr(-2) :
}
```

**Comment by dmester** [comment]
Thank you for reporting this issue. A fix will be included in the next release that will be published in a moment.
